Add gfx940 target for f32/f64 types
ROCmSoftwarePlatform/hipTensor pull request #109
Opened 2023-09-07 18:33 UTC by mkarunan

2023-09-07 18:55 UTC, dlangbe requested changes

2023-09-07 18:55 UTC, dlangbe commented on README.md
> +* AMD CDNA class GPU featuring matrix core support: gfx908, gfx90a as 'gfx9', gfx940
Should read:
AMD CDNA class GPU featuring matrix core support: gfx908, gfx90a, gfx940 as 'gfx9'

2023-09-08 14:55 UTC, cgmillette commented on samples/01_contraction/simple_bilinear_contraction_f32.cpp
> +            || (deviceName.find("gfx90a") != std::string::npos)
Can remove duplicate code and replace with the common.hpp version

2023-09-18 22:22 UTC, cgmillette commented on CMakeLists.txt
> +  TARGETS "gfx908:xnack-;gfx90a:xnack-;gfx90a:xnack+;gfx940:xnack-;gfx940:xnack+" )
@mkarunan for the targets, let's just set gfx940 without xnack. It will default to xnack:any which is sufficient for now

2023-09-20 16:12 UTC, cgmillette approved these changes
LGTM

2023-09-20 16:14 UTC, merged