Add flags needed for clang compiler
ROCmSoftwarePlatform/hipTensor pull request #179
Opened 2024-01-24 03:00 UTC by mkarunan

To transition from hipcc to clang, add additional flags to match the compiler flags generated from hipcc.

2024-03-26 16:47 UTC, cgmillette requested changes
This makes the changes global to the current project.
Can we instead make these changes to the test and samples CMakeLists for the target creation:
target_compile_options($target PRIVATE --driver-mode=g++ )

2024-04-04 19:57 UTC, CongMa13 commented
> This makes the changes global to the current project. Can we instead make these changes to the test and samples CMakeLists for the target creation: target_compile_options($target PRIVATE --driver-mode=g++ )

Add `--driver-mode=g++` as private compile/link option to each target.

2024-04-15 20:12 UTC, CongMa13 submitted a review, later dismissed
lgtm

2024-04-16 15:03 UTC, cgmillette approved these changes, later dismissed

2024-04-16 15:08 UTC, cgmillette approved these changes

2024-04-16 15:08 UTC, merged