Update docs
ROCmSoftwarePlatform/hipTensor pull request #211
Opened 2024-04-15 22:09 UTC by cgmillette

hipTensor needs a docs overhaul to fit the new style, and hipTensor's new API and library dependencies:

* Update what-is-hiptensor
* Update installation.rst
* Update programmers-guide.rst
* Update api-reference.rst

Additional fixes include project configs and doxygen formatting in the code

2024-04-24 17:36 UTC, snow20cm requested changes

2024-04-24 17:36 UTC, snow20cm commented on docs/installation.rst
> +* Minimum LLVM dev package version support is 10.0 (available as ROCm package rocm-llvm-dev).
We only check for llvm 7.0 and above in CMake

2024-04-24 17:36 UTC, snow20cm commented on docs/installation.rst
> +``bilinear_contraction_test_m2n2k2``             Bilinear contraction test [D = alpha * (A x B) + beta * C] with  half, single and mixed precision datatypes of rank 4
and m1n1k1

2024-04-24 17:36 UTC, snow20cm commented on docs/installation.rst
> +* Manually adjust the test cases coverage. Using your favorite text editor, you can modify test YAML configs to affect the test parameter coverage.
Should we specify somewhere that CK only support up to 2G elements in contraction?

2024-04-24 17:36 UTC, snow20cm commented on docs/programmers-guide.rst
> +For those wishing to contribute to the project, please see `Contributing to hipTensor  <https://github.com/ROCm/hipTensor/blob/develop/CONTRIBUTING.md>`_.
dead link

2024-04-24 17:36 UTC, snow20cm commented on docs/contributors-guide.rst
> +Example
rendered content is not what we expect. 

![image](https://github.com/ROCm/hipTensor/assets/13180863/1ef5e86f-8c9d-4e46-9ad2-576513f35d92)

2024-04-24 23:18 UTC, cgmillette commented
Feedback has been incorporated

2024-04-25 14:35 UTC, mkarunan approved these changes, later dismissed

2024-04-25 14:35 UTC, mkarunan commented on docs/contributors-guide.rst
> +<!-- markdownlint-disable ol-prefix -->
<img width="475" alt="contributors_error" src="https://github.com/ROCm/hipTensor/assets/85510608/249db3d1-545a-4c0d-8459-19865f5f0fbd">

Is this the intended behavior?

2024-04-25 14:35 UTC, mkarunan commented on docs/programmers-guide.rst
> +the data is laid out in memory and how they related to each other spatially.
how they are related to each other spatially.

2024-04-25 15:11 UTC, CongMa13 submitted a review, later dismissed
lgtm

2024-04-25 17:48 UTC, cgmillette commented on docs/contributors-guide.rst
> +<!-- markdownlint-disable ol-prefix -->
Fixed

2024-04-25 17:50 UTC, cgmillette commented on docs/programmers-guide.rst
> +the data is laid out in memory and how they related to each other spatially.
fixed

2024-04-26 15:31 UTC, CongMa13 approved these changes
lgtm

2024-04-26 22:39 UTC, merged